"""crear_tabla_tags_osm

Revision ID: 7270d3355cd7
Revises: d5784b813631
Create Date: 2026-04-25 07:43:49.734999

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# IMPORTANTE: Importamos la data desde el seed original para no duplicar código
from modelos.TagsOSM.seed import TAGS_DATA

# revision identifiers, used by Alembic.
revision: str = '7270d3355cd7'
down_revision: Union[str, Sequence[str], None] = 'd5784b813631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    tags_osm_table = op.create_table('tags_osm',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre_humano', sa.String(), nullable=False),
        sa.Column('llave_osm', sa.String(), nullable=False),
        sa.Column('valor_osm', sa.String(), nullable=False),
        sa.Column('descripcion', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_osm_id'), 'tags_osm', ['id'], unique=False)
    op.create_index(op.f('ix_tags_osm_nombre_humano'), 'tags_osm', ['nombre_humano'], unique=True)
    
    # SEED DATA: Usamos la lista importada de modelos.TagsOSM.seed
    op.bulk_insert(tags_osm_table, TAGS_DATA)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_osm_nombre_humano'), table_name='tags_osm')
    op.drop_index(op.f('ix_tags_osm_id'), table_name='tags_osm')
    op.drop_table('tags_osm')
    # ### end Alembic commands ###
