"""Crear tablas iniciales

Revision ID: d5784b813631
Revises: 
Create Date: 2026-02-22 01:27:24.613254

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'd5784b813631'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Asegurar que la extensión postgis esté habilitada
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('push_token', sa.String(length=255), nullable=True),
    sa.Column('ultima_latitud', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('ultima_longitud', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('ultima_conexion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('deseos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('texto_original', sa.Text(), nullable=False),
    sa.Column('tag_osm', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('radio_busqueda_metros', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubicaciones_deseo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deseo_id', sa.UUID(), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre_lugar', sa.String(length=255), nullable=True),
    sa.Column('ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False, spatial_index=False), nullable=False),
    sa.Column('ya_notificado', sa.Boolean(), nullable=True),
    sa.Column('fecha_notificacion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deseo_id'], ['deseos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ubicaciones_deseo_ubicacion', 'ubicaciones_deseo', ['ubicacion'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ubicaciones_deseo_ubicacion', table_name='ubicaciones_deseo', postgresql_using='gist')
    op.drop_table('ubicaciones_deseo')
    op.drop_table('deseos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
