"""add completado fields to deseos

Revision ID: e6895c924742
Revises: d5784b813631
Create Date: 2026-03-09 18:55:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'e6895c924742'
down_revision: Union[str, Sequence[str], None] = 'd5784b813631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deseos', sa.Column('fecha_completado', sa.DateTime(), nullable=True))
    op.add_column('deseos', sa.Column('ubicacion_completado', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=True, spatial_index=False), nullable=True))
    op.create_index('idx_deseos_ubicacion_completado', 'deseos', ['ubicacion_completado'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_deseos_ubicacion_completado', table_name='deseos', postgresql_using='gist')
    op.drop_column('deseos', 'ubicacion_completado')
    op.drop_column('deseos', 'fecha_completado')
    # ### end Alembic commands ###
